### ISSUE TITLE
How do you configure the source connector?

### ISSUE THREAD

**Issue by darthmiguel** [Aegeaner/kafka-connector-redis#2]
Hi, could you please help me to configure your source connector on Apache Kafka 1.0?
Thanks

**Comment by Aegeaner** [comment]
There is a sample configuration definition in the code snippet, which defined the name, meaning and default value of each configuration option: [https://github.com/Aegeaner/kafka-connector-redis/blob/1c6af9f1f26b5732fcabdad098ce28b8677c5175/src/main/java/org/apache/kafka/connect/redis/RedisSourceConfig.java#L41](https://github.com/Aegeaner/kafka-connector-redis/blob/1c6af9f1f26b5732fcabdad098ce28b8677c5175/src/main/java/org/apache/kafka/connect/redis/RedisSourceConfig.java#L41)

**Comment by Aegeaner** [comment]
This connector is tested with Kafka 0.10, but you can build agianst Kafka 1.0 yourself, just change the dependency here: [https://github.com/Aegeaner/kafka-connector-redis/blob/1c6af9f1f26b5732fcabdad098ce28b8677c5175/pom.xml#L44](https://github.com/Aegeaner/kafka-connector-redis/blob/1c6af9f1f26b5732fcabdad098ce28b8677c5175/pom.xml#L44)

**Comment by darthmiguel** [comment]
I need to retrieve data from a list, where is the parameter to point to it?

**Comment by Aegeaner** [comment]
Hi @darthmiguel , I used [https://github.com/leonchen83/redis-replicator](RedisReplicator) as the Redis comand parser, so e.g. the List push command is defined as: [https://github.com/leonchen83/redis-replicator/blob/master/src/main/java/com/moilioncircle/redis/replicator/cmd/impl/LPushCommand.java](LPushCommand.java). The connector wrapped the command using its name as the key, with the serialization of the command as the value.
So in the short, the answer is nothing should you do, just parse the command string like this: [https://github.com/leonchen83/redis-replicator/blob/f6711bd347e644ef53c1d28d7716dea957230150/src/main/java/com/moilioncircle/redis/replicator/cmd/impl/LPushCommand.java#L83](https://github.com/leonchen83/redis-replicator/blob/f6711bd347e644ef53c1d28d7716dea957230150/src/main/java/com/moilioncircle/redis/replicator/cmd/impl/LPushCommand.java#L83)
If you dislike parsing the command string instead of raw redis protocol, feel free to change the value parameter here to `cmd.getRawValues()`: [https://github.com/Aegeaner/kafka-connector-redis/blob/1c6af9f1f26b5732fcabdad098ce28b8677c5175/src/main/java/org/apache/kafka/connect/redis/RedisSourceTask.java#L94](https://github.com/Aegeaner/kafka-connector-redis/blob/1c6af9f1f26b5732fcabdad098ce28b8677c5175/src/main/java/org/apache/kafka/connect/redis/RedisSourceTask.java#L94)

**Comment by darthmiguel** [comment]
So far I haven't changed anything in your code. What I have done is the following
1. create the jar
2. export the jar path to the $CLASSPATH 
3. run connect-distributed worker with the following properties
bootstrap.servers=localhost:9092
group.id=testGroup
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
offset.storage.topic=connect-offsets
offset.storage.replication.factor=1
config.storage.topic=connect-configs
config.storage.replication.factor=1
status.storage.topic=connect-status
status.storage.replication.factor=1
offset.flush.interval.ms=10000
4. create connector json properties
{
       "name":"redis-source-connector",
       "config" :{
               "connector.class":"org.apache.kafka.connect.redis.RedisSourceConnector",
               "tasks.max":"1",
               "host":"localhost",
               "port":"6379",
               "topic":"redis"
       }
}
5. register the connector with
curl -X POST -H "Content-Type: application/json" --data @/Users/miguelmarmol/Documents/kafka-connect-redis/redis-source-config.json http://localhost:8083/connectors | jsonpp

The problem is the topic "redis" is still empty, what I am missing here?

**Comment by Aegeaner** [comment]
Hi @darthmiguel , try running this connector in standalone mode.
